[tool.poetry]
name = "cookiecutter-modern-pypackage"
version = "0.1.0"
description = "Cookiecutter template for a modern Python package."
authors = ["Federico Jaureguialzo <fedejaure@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.4.0"
pytest = "^5.4.2"
pytest-cov = "^2.8.1"
flake8 = "3.7.9"
flakehell = "^0.3.3"
flake8-builtins = "^1.5.3"
flake8-blind-except = "^0.1.1"
flake8-logging-format = "^0.6.0"
isort = "^4.3.21"

[tool.flakehell]
format = "grouped"
max_line_length = 120
show_source = true

[tool.flakehell.plugins]
pyflakes = ["+*"]
pycodestyle = ["+*"]
mccabe = ["+*"]
"flake8-*" = ["+*"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
known_third_party = []

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
